env:
- VERSION_SUFFIX=aa-ci-$TRAVIS_BRANCH-$TRAVIS_BUILD_NUMBER

language: csharp
mono: latest
dotnet: 2.1

install:
- dotnet restore

script:
- dotnet build -c Release --version-suffix $VERSION_SUFFIX
- dotnet test Hgk.Zero.Tests/Hgk.Zero.Tests.csproj
# pack step not necessary; build is configured to make package

deploy:
  - on:
      branch: master
    skip_cleanup: true
    provider: script
    script: dotnet nuget push Hgk.Zero/bin/Release/*-$VERSION_SUFFIX.nupkg --api-key $NUGET_API_KEY --source $NUGET_SOURCE
  - on:
      branch: docfx-from-ci
    skip_cleanup: true
    provider: script
    script: bash scripts/docfx_to_gh_pages.sh
