dist: xenial

env:
  global:
    - CONFIGURATION=Release
    - VERSION_SUFFIX=$(printf 'aa-ci-%s-%08d' "$TRAVIS_BRANCH" "$TRAVIS_BUILD_NUMBER")
    - DOTNET_CLI_TELEMETRY_OPTOUT=1
    - DOTNET_SKIP_FIRST_TIME_EXPERIENCE=1
    - GITHUB_DOC_REPO_OWNER=psmay
    - GITHUB_DOC_REPO=Hgk.Zero

language: csharp
mono: none
dotnet: 2.1

install:
  - dotnet restore

script:
  - dotnet build -c Release --version-suffix $VERSION_SUFFIX
  - dotnet test Hgk.Zero.Tests/Hgk.Zero.Tests.csproj
  # pack step not necessary; build is configured to make package

deploy:
  - on:
      branch: master
    skip_cleanup: true
    provider: script
    script: dotnet nuget push Hgk.Zero/bin/Release/*-$VERSION_SUFFIX.nupkg --api-key $NUGET_API_KEY --source $NUGET_SOURCE
  - on:
      branch: updates-compilation
    skip_cleanup: true
    provider: script
    script: bash scripts/documentation_all.sh
